ADD_CUSTOM_TARGET( examples )
INCLUDE_DIRECTORIES(include ${ROOT_INCLUDE_DIRS} ${EIGEN3_INCLUDE_DIR})

MACRO( ADD_PATHFINDER_EXAMPLE _name )
    set(testName "GBL_${_name}") 
    ADD_EXECUTABLE( ${testName} ${ARGN} )
    TARGET_LINK_LIBRARIES( ${testName} ${PROJECT_NAME} ${ROOT_LIBS})
    INSTALL( TARGETS ${testName} DESTINATION bin )
ENDMACRO()

ADD_PATHFINDER_EXAMPLE( example1 example1.cpp  )
ADD_PATHFINDER_EXAMPLE( example2 example2.cpp  )
ADD_PATHFINDER_EXAMPLE( example3 example3.cpp  )
ADD_PATHFINDER_EXAMPLE( example4 example4.cpp  )
ADD_PATHFINDER_EXAMPLE( exampleComposedGeo exampleComposedGeo.cpp exampleUtilCdc.cpp )
ADD_PATHFINDER_EXAMPLE( exampleComposedKin exampleComposedKin.cpp exampleUtilCdc.cpp )
ADD_PATHFINDER_EXAMPLE( exampleDc exampleDc.cpp )
ADD_PATHFINDER_EXAMPLE( exampleSit exampleSit.cpp )
